#!/usr/bin/env bash
set -euf -o pipefail

attrs() {
  local attr
  for attr ; do printf ' %s="%s"' "${attr%%=*}" "${attr#*=}" ; done
}

js() {
  node --print "($1)"
}

outercircum="$(js "$3")"
innercircum="$(js "Math.round(0.88 * $outercircum)")"
outerradius="$(js "$outercircum / 2")"
innerradius="$(js "$innercircum / 2")"

cat <<EOF
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="$(js "$3")px" height="$(js "$3")px"$(attrs "${@:4}")>
  <!-- Copyright (c) 2017 Sanctuary -->
  <path
    fill-rule="evenodd"
    fill="$1"
    d="M $outerradius,0
       a $outerradius,$outerradius 0 0,1 0,$outercircum
       a $outerradius,$outerradius 0 0,1 0,-$outercircum
       Z
       m 0,$(js "$outerradius - $innerradius")
       a $innerradius,$innerradius 0 0,1 0,$innercircum
       a $innerradius,$innerradius 0 0,1 0,-$innercircum
       Z
       $(js "require('opentype.js')
             .loadSync('$2')
             .getPath('S', 0.298 * $3, 0.755 * $3, 0.72 * $3)  // x, y, font-size
             .toPathData()
             .match(/[A-Z][^A-Z]*/g)
             .join('\n       ')
             .replace(/[A-Z](?=[^ ])/g, '$& ')")"
    />
</svg>
EOF
